# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "PROS Documentation"
license = "MPL 2.0"
licenselink = "https://github.com/purduesigbots/prosdocs/blob/master/LICENSE.md"
description = ""
homepage = "http://pros.cs.purdue.edu/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Purdue ACM SIGBOTS"
  homepage = "http://purduesigbots.com"
